server:
  port: 8082

spring:
  application:
    name: platform-cbs
  datasource:
    url: jdbc:postgresql://localhost:5433/platformdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-expiration: 604800000
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

logging:
  level:
    com.platform: DEBUG
    org.springframework.security: DEBUG

# Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
