server:
  port: 8084

spring:
  application:
    name: platform-co
  datasource:
    url: jdbc:postgresql://localhost:5433/platformdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  jackson:
    time-zone: Europe/Istanbul
    date-format: yyyy-MM-dd HH:mm:ss

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

logging:
  level:
    com.platform: DEBUG
    org.springframework.security: DEBUG

# Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
